use_frameworks!

platform :ios, '10.0'

target 'JCustomSegmentControl_Example' do
  pod 'JCustomSegmentControl', :path => '../'

  target 'JCustomSegmentControl_Tests' do
    inherit! :search_paths

    
  end
end
